### ISSUE TITLE
Feature Request: Traders and json?

### ISSUE THREAD

**Issue by CWXDEV** [refringe/spt-dev-vscode-extension#1]
Ayo i have two questions:

- Can traders be included into this?
- Can this work on Json files?

thanks for updating this

**Comment by refringe** [comment]
JSON support has been added in [v1.0.2](https://github.com/refringe/spt-id-highlighter/releases/tag/v1.0.2). Should be updated on the marketplace.

I'll look into traders soon. Thanks for the suggestions!

**Comment by refringe** [comment]
Resolved in v1.1.0
